//
//  DataBase.swift
//  WeHubbyTests
//
//  Created by apprenant50 on 17/06/2022.
//

import Foundation
import MapKit


var categoris : [Categoriz] = [Categoriz(nameCategory: .artist, picCategory: "articon"),
                               Categoriz(nameCategory: .collec, picCategory: "basketicon"),
                               Categoriz(nameCategory: .cook, picCategory: "cookicon"),
                               Categoriz(nameCategory: .culture, picCategory: "theatreicon"),
                               Categoriz(nameCategory: .deco, picCategory: "decoicon"),
                               Categoriz(nameCategory: .games, picCategory: "gameicon"),
                               Categoriz(nameCategory: .garden, picCategory: "gardenicon"),
                               Categoriz(nameCategory: .brico, picCategory: "bricoicon"),
                               Categoriz(nameCategory: .info, picCategory: "infoicon"),
                               Categoriz(nameCategory: .lecture, picCategory: "booksicon"),
                               Categoriz(nameCategory: .manu, picCategory: "coutureicon"),
                               Categoriz(nameCategory: .relax, picCategory: "relaxicon"),
                               Categoriz(nameCategory: .society, picCategory: "jeuxicon"),
                               Categoriz(nameCategory: .sport, picCategory: "runicon")]

var userProfiles : [Friends] = [
    Friends(userPsedo: "Cindie", userBio: "J'adore les créations manuelles mais j'aimerai découvrir de nouveaux loisirs et rencontrer de nouvelles personnes", userTag: [.crea, .nature, .relaxa], userCover: "malta", pictures: ["epoxy", "accrobranche", "poterie", "couture", "malta", "tricotevent", "tricot", "coutureevent"], pastEvents: [], futureEvents: [], isCurrentUser: true, favoriteCategory: [categoris[0], categoris[4], categoris[11]], isOnline: true, userPicture: "cindie", isFriend: false, ville: "Roubaix"),
    Friends(userPsedo: "Cesaltina", userBio: "Couture, broderie, scrapbooking... J'aimerai partager avec des personnes de la communauté", userTag: [.crea, .sante], userCover: "couture", pictures: ["couture"], pastEvents: [], futureEvents: [], isCurrentUser: false, favoriteCategory: [categoris[5], categoris[10], categoris[9]], isOnline: true, userPicture: "cesal", isFriend: true, ville: "Lyon"),
    Friends(userPsedo: "Morgan", userBio: "Fan de cuisine et de relaxation, j'aimerai m'ouvrir à d'autres horizons", userTag: [.relaxa], userCover: "poterie", pictures: ["poterie", "broderie", "epoxy"], pastEvents: [], futureEvents: [], isCurrentUser: false, favoriteCategory: [categoris[6], categoris[10], categoris[8]], isOnline: false, userPicture: "morgan", isFriend: false, ville: "Lyon"),
    Friends(userPsedo: "Dimitri", userBio: "Heureux papa depuis peu, je veux découvrir de nouvelles activités manuelles & des activités à distance.", userTag: [.cook, .epicu], userCover: "notion", pictures: [], pastEvents: [], futureEvents: [], isCurrentUser: false, favoriteCategory: [categoris[13], categoris[7], categoris[8], categoris[9]], isOnline: false, userPicture: "dimitri", isFriend: true, ville: "Toulouse"),
    Friends(userPsedo: "Looping", userBio: "Les jeux vidéos et l'informatique c'est bien, mais j'aimerai me dégourdir les jambes...", userTag: [.nuit, .crea], userCover: "wanda", pictures: [], pastEvents: [], futureEvents: [], isCurrentUser: false, favoriteCategory: [categoris[9], categoris[8], categoris[12]], isOnline: true, userPicture: "kelian", isFriend: false, ville: "Toulouse"),
    Friends(userPsedo: "Toto le dozo", userBio: "Bricoleur du dimanche, je geek beaucoup mais j'ai besoin d'air.", userTag: [.aventu, .nuit, .nature], userCover: "ricky", pictures: [], pastEvents: [], futureEvents: [], isCurrentUser: false, favoriteCategory: [categoris[1], categoris[5], categoris[8], categoris[7]], isOnline: true, userPicture: "lol", isFriend: true, ville: "Valenciennes")]


var loisirs : [Hobbies] = [Hobbies(hobbyName: "Couture", hobbyDescription: "Une couture est l'assemblage de deux ou plusieurs pièces à l'aide de fil à coudre, soit manuellement avec une aiguille, soit en utilisant une machine à coudre ou une surjeteuse. ", subtitleSwipe: "Assemblez des pièces de tissus à l'aide d'une aiguille ou d'une machine.", hobbyPic: "couture", hobbyTags: [.crea, .relaxa], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[10]),
                           Hobbies(hobbyName: "Broderie", hobbyDescription: "La broderie est un art de décoration des tissus qui consiste à ajouter sur un tissu un motif plat ou en relief fait de fils simples, parfois en intégrant des matériaux tels que des paillettes, des perles, voire des pierres précieuses.", subtitleSwipe: "Embellisez des pièces de tissus à la main", hobbyPic: "broderie", hobbyTags: [.crea], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[10]),
                           Hobbies(hobbyName: "Poterie", hobbyDescription: "La poterie consiste à créer des vases et récipients à la main à partir de terre cuite.", subtitleSwipe: "Créez vos propres vases et récipients", hobbyPic: "poterie", hobbyTags: [.crea], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[10]),
                           Hobbies(hobbyName: "Bougies artisanales", hobbyDescription: "La création de bougies artisanales permet de faire et personnaliser à souhait des bougies de toutes tailles, de toutes formes et de toutes odeurs.", subtitleSwipe: "Créez vos propres bougies personnalisées", hobbyPic: "bougie", hobbyTags: [.crea], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[10]),
                           Hobbies(hobbyName: "Résines d'epoxy", hobbyDescription: "La résine d'epoxy permet de faire énormément d'objets différents à partir de ce matériau, de les personnalisé grâce à des couleurs et différentes formes grâce à des moules.", subtitleSwipe: "Créez tout type d'objet de toute forme grâce à la résine d'epoxy", hobbyPic: "epoxy", hobbyTags: [.crea], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[10]),
                           Hobbies(hobbyName: "Théâtre", hobbyDescription: "Aller au théâtre pour y voir des pièces dramatiques, comiques, des tragédies... Pouvoir voir des représentations des plus grandes pièces connues à des petites productions.", subtitleSwipe: "Découvrez le plaisir d'assister à une pièce de théâtre seul ou à plusieurs...", hobbyPic: "theatre", hobbyTags: [.art], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[3]),
                           Hobbies(hobbyName: "Cinéma", hobbyDescription: "Le cinéma est un art du spectacle. En français, il est désigné comme le « septième art », d'après l'expression du critique Ricciotto Canudo dans les années 19201. L’art cinématographique se caractérise par le spectacle proposé au public sous la forme d’un film, c’est-à-dire d’un récit (fictionnel ou documentaire), véhiculé par un support (pellicule souple, bande magnétique, contenant numérique) qui est enregistré puis lu par un mécanisme continu ou intermittent qui crée l’illusion d’images en mouvement, ou par un enregistrement et une lecture continue de données informatiques.", subtitleSwipe: "Le 7ème art sous toutes ses formes, de la petite à la grande production.", hobbyPic: "cinema", hobbyTags: [.art, .relaxa], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[3]),
                           Hobbies(hobbyName: "Futsal", hobbyDescription: "Le futsal ou football en salle est un sport collectif apparenté au football. Comme lui, il se joue principalement au pied avec un ballon sphérique. Il oppose deux équipes de cinq joueurs dans un gymnase, sur un terrain de handball. L'objectif de chaque équipe est de mettre le ballon dans le but adverse, sans utiliser les bras, et de le faire plus souvent que l'autre équipe.", subtitleSwipe: "Pouvoir jouer au football sans craindre la météo, et avec moins de joueurs... C'est le Futsal", hobbyPic: "futsal", hobbyTags: [.sport], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[1]),
                           Hobbies(hobbyName: "Peinture", hobbyDescription: "La peinture est une forme artistique dont les diverses techniques consistent à appliquer manuellement ou mécaniquement, sur une surface, des couleurs sous forme de pigments mélangés à un liant ou un diluant. Les artistes peintres s'expriment sur des supports tels que la toile, le papier, le bois, etc.", subtitleSwipe: "Peinture à l'huile, à l'eau, à l'aquarelle... découvrez cette activité artistique", hobbyPic: "peinture", hobbyTags: [.art, .crea, .relaxa], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[0]),
                           Hobbies(hobbyName: "Dessin", hobbyDescription: "Le dessin est une technique de représentation visuelle sur un support plat. Le terme « dessin » désigne à la fois l'action de dessiner, l'ouvrage graphique qui en résulte, et la forme d'un objet quelconque.", subtitleSwipe: "Dessiner au fusain, au crayon... Plein de technique pour apprendre à dessiner", hobbyPic: "dessin", hobbyTags: [.relaxa, .crea, .art], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[0]),
                           Hobbies(hobbyName: "Musique", hobbyDescription: "La musique est un art et une activité culturelle consistant à combiner sons et silences au cours du temps. Les paramètres principaux sont le rythme (façon de combiner les sons dans le temps), la hauteur (combinaison dans les fréquences), les nuances et le timbre. Elle est aujourd'hui considérée comme une forme de poésie moderne.", subtitleSwipe: "Découvrez de nouveaux ", hobbyPic: "musique", hobbyTags: [.art, .crea], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[0]),
                           Hobbies(hobbyName: "Basketball", hobbyDescription: "Le basket-ball , est un sport collectif de balle opposant deux équipes de cinq joueurs sur un terrain rectangulaire. L'objectif de chaque équipe est de faire passer un ballon au sein d'un arceau de 45 cm5 de diamètre, fixé à un panneau et placé à 3,05 m du sol : le panier. Chaque panier inscrit rapporte deux points à son équipe, à l'exception des tirs effectués au-delà de la ligne des trois points (qui rapportent trois points) et des lancers francs accordés à la suite d'une faute (qui rapportent un point). L'équipe avec le nombre de points le plus important remporte la partie.", subtitleSwipe: "Jouer en équipe de 5 pour marquer le plus de panier pour battre l'équipe adversaire, s'amuser, de jour comme de nuit, dedans comme dehors.", hobbyPic: "basket", hobbyTags: [.sport, .sante], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[1]),
                           Hobbies(hobbyName: "Musique électronique", hobbyDescription: "La musique électronique est un type de musique conçu dans les années 1950 avec des générateurs de signaux et de sons synthétiques. Avant de pouvoir être utilisée en temps réel, elle a été enregistrée sur bande magnétique, ce qui permettait aux compositeurs de manier aisément les sons, par exemple dans l'utilisation de boucles répétitives superposées.", subtitleSwipe: "Pouvoir faire de la musique grâce à un ordinateur, découvrez la magie de la musique électronique.", hobbyPic: "box", hobbyTags: [.crea, .music], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[0]),
                           Hobbies(hobbyName: "Yoga", hobbyDescription: "Le yoga est une discipline ou pratique commune à plusieurs époques et courants, visant, par la méditation, l'ascèse et les exercices corporels, à réaliser l'unification de l'être humain dans ses aspects physique, psychique et spirituel.", subtitleSwipe: "Se relaxer, gagner en souplesse, apaiser ses chakras, apaiser l'esprit, le yoga a de multiples vertues.", hobbyPic: "yoga", hobbyTags: [.sante, .sport, .nature, .relaxa], hobbyEvents: [], hobbyComs: [], tutoHobby: [], category: categoris[11])]

var evenements : [Events] = [Events(eventName: "Tricot Participatif", eventHobby: loisirs[0], eventPlace: "Roubaix", eventDate: "23/06/2022", eventDesc: "Venez participer à notre premier tricot participatif de Roubaix. Les différents dons seront reversés à la ville. Le but étant de créer une grande fresque pour l'évènement musicale de l'été.", type: .isIn, eventPicture: "coutureevent", participants: [userProfiles[0], userProfiles[1], userProfiles[2], userProfiles[5]], participate: true, comms: [], coordonnnes: CLLocationCoordinate2D(latitude: 50.690738, longitude: 3.189492), lieuComplet: "La Condition Publique, 14 Place du Général Faidherbe, 59100 Roubaix", catego: categoris[10]),
                             Events(eventName: "Tricot Solidaire", eventHobby: loisirs[0], eventPlace: "Lille", eventDate: "17/07/2022", eventDesc: "Venez participer à notre premier tricot participatif de Lille. Les différents dons seront reversés à la ville. Le but étant de créer une grande fresque pour la grande Braderie de Lille.", type: .isOut, eventPicture: "tricot", participants: [userProfiles[0], userProfiles[1], userProfiles[2]], participate: true, comms: [], coordonnnes: CLLocationCoordinate2D(latitude: 50.629256, longitude: 3.058154), lieuComplet: "Théâtre Sebastopol, Place Sebastopol, 59000 Lille", catego: categoris[10]),
                             Events(eventName: "Tricotathlon", eventHobby: loisirs[0], eventPlace: "Tourcoing", eventDate: "01/08/2022", eventDesc: "Venez participer à notre premier tricotathlon de Tourcoing. Les différents dons seront reversés à la ville. Le but étant de créer une grande fresque pour afficher à la mairie.", type: .isIn, eventPicture: "tricotevent", participants: [userProfiles[0], userProfiles[1], userProfiles[2]], participate: true, comms: [], coordonnnes: CLLocationCoordinate2D(latitude: 50.723749, longitude: 3.160691), lieuComplet: "Mairie de Tourcoing, 10 Place Victor Hassebroucq, 59200 Tourcoing", catego: categoris[10]),
                             Events(eventName: "Cours de guitare sèche", eventHobby: loisirs[10], eventPlace: "Lyon", eventDate: "01/08/2022", eventDesc: "Pratiquant la guitare depuis 20 ans, je propose un cours d'initiation à distance", type: .distanc, eventPicture: "eventguit", participants: [userProfiles[1]], participate: false, comms: [], coordonnnes: CLLocationCoordinate2D(latitude: 45.764043, longitude: 4.835659), lieuComplet: "http://meet.google.com", catego: categoris[0]),
                             Events(eventName: "Yoga collectif", eventHobby: loisirs[13], eventPlace: "Lyon", eventDate: "17/07/2022", eventDesc: "Venez communier avec la nature lors d'un cours de yoga collectif au parc de la tête d'Or.", type: .isOut, eventPicture: "yogaout", participants: [userProfiles[1], userProfiles[2]], participate: false, comms: [], coordonnnes: CLLocationCoordinate2D(latitude: 45.7785792, longitude: 4.8520963), lieuComplet: "Parc de la tête d'Or, 69006 Lyon", catego: categoris[11]),
                             Events(eventName: "Cours de yoga", eventHobby: loisirs[13], eventPlace: "La Madeleine", eventDate: "06/07/2022", eventDesc: "Cours de yoga collectif au Yoga Mood de la Madeleine, ateleir découverte, initiation et relaxation.", type: .isIn, eventPicture: "yogacours", participants: [userProfiles[0], userProfiles[5]], participate: true, comms: [], coordonnnes: CLLocationCoordinate2D(latitude: 50.653350830078125, longitude: 3.0765810012817383), lieuComplet: "8 Rue Carnot, 59110 La Madeleine", catego: categoris[11])]

let typeEvents : [TypeEvents] = [TypeEvents.isIn, TypeEvents.isOut, TypeEvents.distanc]
